---
title: "LMwithPred"
author: "Flora Soto"
date: "11/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Interduction  
This is the linear model with prediction problem.  
Predict strength scores using data from the following web site  

```{r}
dataF <- read.csv(file="http://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt", sep="", header=TRUE)
```

```{r include=FALSE}
require(tidyverse)
require(tigerstats)
require(rgl)
require(knitr)
```
  
###Plot scatterplot

```{r}
plot(SIMS~ARM,data=dataF) 
```

```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=ARM))
```
##Now add in scatterplot

```{r}
basicNN + geom_point() + geom_smooth(method=lm)
```
 
```{r}
model.1 <- lm(SIMS~ARM,data=dataF)
summary.lm(model.1)
New=data.frame(GRIP=94,ARM=88)
predict.lm(model.1,New,interval="prediction")
```  
```{r}
plot(SIMS~GRIP,data=dataF) 
```

```{r}
basicNN <- ggplot(dataF,aes(y=SIMS,x=GRIP))
```
##Now add in scatterplot

```{r}
basicNN + geom_point() + geom_smooth(method=lm)
```


```{r}
model.2 <- lm(SIMS~GRIP,data=dataF)
summary.lm(model.2)
predict.lm(model.2,New,interval="prediction")
```


```{r}
model.3 <- lm(SIMS~ARM+GRIP,data=dataF)
summary.lm(model.3)
predict.lm(model.3,New,interval="prediction")
```